LANGUAGES = sorted([
	('', 'Auto-detect'),
	('html', 'HTML'),
	('css', 'CSS'),
	('javascript', 'JavaScript'),
	('cs', 'C#'),
	('cpp', 'C++'),
	('python', 'Python'),
	('ruby', 'Ruby'),
	('haskell', 'Haskell'),
	('php', 'PHP'),
	('coffeescript', 'CoffeeScript'),
	('perl', 'Perl'),
	('go', 'Go'),
	('scss', 'SCSS'),
	('markdown', 'Markdown'),
	('django', 'Django'),
	('json', 'JSON'),
	('lua', 'Lua'),
	('c', 'C'),
	('bash', 'Bash')
], key=lambda value: value[1])