LANGUAGES = [
	('', 'Other'),
	('html', 'HTML'),
	('css', 'CSS'),
	('javascript', 'JavaScript'),
	('cs', 'C-Sharp'),
	('cpp', 'C++'),
	('python', 'Python'),
	('ruby', 'Ruby'),
	('haskell', 'Haskell'),
	('php', 'PHP'),
	('coffeescript', 'CoffeeScript'),
	('perl', 'Perl'),
	('go', 'Go'),
	('scss', 'SCSS'),
	('markdown', 'Markdown'),
	('django', 'Django'),
	('json', 'JSON'),
	('lua', 'Lua'),
	('c', 'c'),
	('bash', 'Bash')
]